content = ""
layer = 0
show = false

ease = "fade"
duration = 0

[x]
value = 0
duration = 0
ease = "linear"

[x.velocity]
value = 0
duration = 0
ease = "linear"

[y]
value = 0
duration = 0
ease = "linear"

[y.velocity] 
value = 0
duration = 0
ease = "linear"

[rotation]
value = 0
duration = 0
ease = "linear"

[rotation.velocity] 
value = 0
duration = 0
ease = "linear"

[alpha]
value = 0
duration = 0
ease = "linear"

[zoom]
value = 100
duration = 0
ease = "linear"

[in]
value = "fade"
duration = 0
ease = "linear"

[out]
value = "fade"
duration = 0
ease = "linear"